config-version: 1.2
enable-alert-on-join: true
kick-on-invalid-item-packet: true
# Исправляет проблемы с hex
disable-hover-message: false
kick-on-invalid-transaction: true
mitigations:
  damage-reduce: 0.1