config-version: 1.0
enable-alert-on-join: true
kick-on-invalid-item-packet: true
verbose-to-console: false
# В минутах
reset-time: 3
# Исправляет проблемы с hex
disable-hover-message: false
kick-on-invalid-transaction: true
visual:
  metadata-hider:
    # Должны ли мы скрывать здоровье?
    health: true
    # Должны ли мы скрывать поглощение?
    absorption: true
    # Должны ли мы скрывать насыщенность?
    saturation: true
    # Должны ли мы скрывать эффекты?
    effects: true
    # Должны ли мы скрывать опыт?
    xp: true
    # Должны ли мы скывать обход через FuntimeMode TargetHud
    fix-scoreboard: false
mitigations:
  damage-reduce: 0.1