config-version: 1.0
enable-alert-on-join: true
kick-on-invalid-item-packet: true
verbose-to-console: false
# В минутах
reset-time: 3
# Исправляет проблемы с hex
disable-hover-message: false
kick-on-invalid-transaction: true
mitigations:
  damage-reduce: 0.1